<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">
 
# Ensembles and Random Forests
 
_Author: Joseph Nelson (DC)_

*Adapted from Chapter 8 of [An Introduction to Statistical Learning](http://www-bcf.usc.edu/~gareth/ISL/)*

---

## Learning Objectives

Students will be able to:

- Understand how and why decision trees can be improved using bagging and random forests.
- Build random forest models for classification and regression.
- Know how to extract the most important predictors in a random forest model.


In [171]:
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

%matplotlib inline

<a id="introduction"></a>
## Introduction

### What is Ensembling?

**Ensemble learning (or "ensembling")** is the process of combining several predictive models in order to produce a combined model that is more accurate than any individual model. For example, given predictions from several models we could:

- **Regression:** Take the average of the predictions.
- **Classification:** Take a vote and use the most common prediction.

For ensembling to work well, the models must be:

- **Accurate:** They outperform the null model.
- **Independent:** Their predictions are generated using different processes.

**The big idea:** If you have a collection of individually imperfect (and independent) models, the "one-off" mistakes made by each model are probably not going to be made by the rest of the models, and thus the mistakes will be discarded when you average the models.

There are two basic **methods for ensembling:**

- Manually ensembling your individual models.
- Using a model that ensembles for you.

<a id="part-one"></a>
## Part 1: Manual Ensembling

What makes an effective manual ensemble?

- Different types of **models**.
- Different combinations of **features**.
- Different **tuning parameters**.

![Machine learning flowchart](./assets/crowdflower_ensembling.jpg)

*Machine learning flowchart created by the [winner](https://github.com/ChenglongChen/Kaggle_CrowdFlower) of Kaggle's [CrowdFlower competition](https://www.kaggle.com/c/crowdflower-search-relevance)*.

### Comparing Manual Ensembling With a Single Model Approach

**Advantages of manual ensembling:**

- It increases predictive accuracy.
- It's easy to get started.

**Disadvantages of manual ensembling:**

- It decreases interpretability.
- It takes longer to train.
- It takes longer to predict.
- It is more complex to automate and maintain.
- Small gains in accuracy may not be worth the added complexity.

<a id="part-two"></a>
## Part 2: Bagging

The primary weakness of **decision trees** is that they don't tend to have the best predictive accuracy. This is partially because of **high variance**, meaning that different splits in the training data can lead to very different trees.

**Bagging** is a general-purpose procedure for reducing the variance of a machine learning method but is particularly useful for decision trees. Bagging is short for **bootstrap aggregation**, meaning the aggregation of bootstrap samples.

A **bootstrap sample** is a random sample with replacement. So, it has the same size as the original sample but might duplicate some of the original observations.

In [172]:
# Set a seed for reproducibility.
np.random.seed(1)

In [173]:
# Create an array of 1 through 20.
nums = np.arange(1,21)
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [174]:
# Sample that array 20 times with replacement.
np.random.choice(nums, size=20, replace=True)

array([ 6, 12, 13,  9, 10, 12,  6, 16,  1, 17,  2, 13,  8, 14,  7, 19,  6,
       19, 12, 11])

**How does bagging work (for decision trees)?**

1. Grow B trees using B bootstrap samples from the training data.
2. Train each tree on its bootstrap sample and make predictions.
3. Combine the predictions:
    - Average the predictions for **regression trees**.
    - Take a vote for **classification trees**.

Notes:

- **Each bootstrap sample** should be the same size as the original training set. (It may contain repeated rows.)
- **B** should be a large enough value that the error seems to have "stabilized".
- The trees are often **grown deep** so that they have low bias/high variance.

Bagging increases predictive accuracy by **reducing the variance**, similar to how cross-validation reduces the variance associated with train/test split (for estimating out-of-sample error) by splitting many times an averaging the results.

<a id="manual-bagged"></a>
## Manually Implementing Bagged Decision Trees (with B=10)

In [175]:
# Read in and prepare the vehicle training data.
path = Path('.', 'data', 'vehicles_train.csv')
train = pd.read_csv(path)
train

price  year   miles  doors  vtype
0   22000  2012   13000      2    car
1   14000  2010   30000      2    car
2   13000  2010   73500      4    car
3    9500  2009   78000      4    car
4    9000  2007   47000      4    car
5    4000  2006  124000      2    car
6    3000  2004  177000      4    car
7    2000  2004  209000      4  truck
8    3000  2003  138000      2    car
9    1900  2003  160000      4    car
10   2500  2003  190000      2  truck
11   5000  2001   62000      4    car
12   1800  1999  163000      2  truck
13   1300  1997  138000      4    car

In [176]:
# Transform "vtype" to "is_truck"
train.loc[:,'is_truck'] = train.loc[:,'vtype'].map({'car':0,'truck':1})
train.drop('vtype',axis=1, inplace=True)
train

price  year   miles  doors  is_truck
0   22000  2012   13000      2         0
1   14000  2010   30000      2         0
2   13000  2010   73500      4         0
3    9500  2009   78000      4         0
4    9000  2007   47000      4         0
5    4000  2006  124000      2         0
6    3000  2004  177000      4         0
7    2000  2004  209000      4         1
8    3000  2003  138000      2         0
9    1900  2003  160000      4         0
10   2500  2003  190000      2         1
11   5000  2001   62000      4         0
12   1800  1999  163000      2         1
13   1300  1997  138000      4         0

In [177]:
# Set a seed for reproducibility.
np.random.seed(123)

In [178]:
# Create ten bootstrap samples (which will be used to select rows from the DataFrame).
nums = np.arange(14)
samples = [np.random.choice(nums, size=14, replace=True) for _ in range(10)]
samples

[array([13,  2, 12,  2,  6,  1,  3, 10, 11,  9,  6,  1,  0,  1]),
 array([ 9,  0,  0,  9,  3, 13,  4,  0,  0,  4,  1,  7,  3,  2]),
 array([ 4,  7,  2,  4,  8, 13,  0,  7,  9,  3, 12, 12,  4,  6]),
 array([ 1,  5,  6, 11,  2,  1, 12,  8,  3, 10,  5,  0, 11,  2]),
 array([10, 10,  6, 13,  2,  4, 11, 11, 13, 12,  4,  6, 13,  3]),
 array([10,  0,  6,  4,  7, 11,  6,  7,  1, 11, 10,  5,  7,  9]),
 array([ 2,  4,  8,  1, 12,  2,  1,  1,  3, 12,  5,  9,  0,  8]),
 array([11,  1,  6,  3,  3, 11,  5,  9,  7,  9,  2,  3, 11,  3]),
 array([ 3,  8,  6,  9,  7,  6,  3,  9,  6, 12,  6, 11,  6,  1]),
 array([13, 10,  3,  4,  3,  1, 13,  0,  5,  8, 13,  6, 11,  8])]

In [179]:
# Show the rows for the first decision tree.
train.iloc[samples[0],:]

price  year   miles  doors  is_truck
13   1300  1997  138000      4         0
2   13000  2010   73500      4         0
12   1800  1999  163000      2         1
2   13000  2010   73500      4         0
6    3000  2004  177000      4         0
1   14000  2010   30000      2         0
3    9500  2009   78000      4         0
10   2500  2003  190000      2         1
11   5000  2001   62000      4         0
9    1900  2003  160000      4         0
6    3000  2004  177000      4         0
1   14000  2010   30000      2         0
0   22000  2012   13000      2         0
1   14000  2010   30000      2         0

In [180]:
# Read in and prepare the vehicle testing data.
path = Path('.','data','vehicles_test.csv')
test = pd.read_csv(path)
test.loc[:,'is_truck'] = test.loc[:,'vtype'].map({'car':0,'truck':1})
test.drop('vtype',axis=1, inplace=True)
test

price  year   miles  doors  is_truck
0   3000  2003  130000      4         1
1   6000  2005   82500      4         0
2  12000  2010   60000      2         0

In [181]:
# Import decision tree regressor
from sklearn.tree import DecisionTreeRegressor

In [182]:
# Grow each tree deep.
treereg = DecisionTreeRegressor(max_depth=None, random_state=123)

In [183]:
# Define testing data.
X_test = test.iloc[:,1:]
y_test = test.iloc[:,0]

In [184]:
# Grow one tree for each bootstrap sample and make predictions on testing data.
predictions = []

for sample in samples:
    X_train = train.iloc[sample, 1:]
    y_train = train.iloc[sample, 0]
    treereg.fit(X_train, y_train)
    y_pred = treereg.predict(X_test)
    predictions.append(y_pred)


In [185]:
predictions

[array([  1300.,   5000.,  14000.]),
 array([  1300.,   1300.,  13000.]),
 array([  3000.,   3000.,  13000.]),
 array([  4000.,   5000.,  13000.]),
 array([  1300.,   5000.,  13000.]),
 array([  4000.,   5000.,  14000.]),
 array([  4000.,   4000.,  13000.]),
 array([  4000.,   5000.,  13000.]),
 array([ 3000.,  5000.,  9500.]),
 array([ 4000.,  5000.,  9000.])]

In [186]:
test

price  year   miles  doors  is_truck
0   3000  2003  130000      4         1
1   6000  2005   82500      4         0
2  12000  2010   60000      2         0

In [187]:
# Convert predictions from list to NumPy array.
predictions = np.array(predictions)
predictions

array([[  1300.,   5000.,  14000.],
       [  1300.,   1300.,  13000.],
       [  3000.,   3000.,  13000.],
       [  4000.,   5000.,  13000.],
       [  1300.,   5000.,  13000.],
       [  4000.,   5000.,  14000.],
       [  4000.,   4000.,  13000.],
       [  4000.,   5000.,  13000.],
       [  3000.,   5000.,   9500.],
       [  4000.,   5000.,   9000.]])

In [188]:
# Average predictions.
np.mean(predictions, axis=0) #axis=0 makes it go down the rows to get mean

array([  2990.,   4330.,  12450.])

In [189]:
# Calculate RMSE.
from sklearn import metrics

y_pred = np.mean(predictions, axis=0)
metrics.mean_absolute_error(y_test, y_pred)

710.0

<a id="manual-sklearn"></a>
## Bagged Decision Trees in `scikit-learn` (with B=500)

In [190]:
# Define the training and testing sets.
X_train = train.iloc[:,1:]
y_train = train.iloc[:,0]
X_test = test.iloc[:,1:]
y_test = test.iloc[:,0]

In [191]:
# Instruct BaggingRegressor to use DecisionTreeRegressor as the "base estimator."
from sklearn.ensemble import BaggingRegressor
bagreg = BaggingRegressor(DecisionTreeRegressor(), n_estimators=500, bootstrap=True, oob_score=True, random_state=1)

In [192]:
# Fit and predict.
bagreg.fit(X_train, y_train)
y_pred = bagreg.predict(X_test)
y_pred

array([  3344.2,   5395. ,  12902. ])

In [193]:
# Calculate RMSE.
metrics.mean_absolute_error(y_test, y_pred)

617.06666666666661

<a id="oos-error"></a>
## Estimating Out-of-Sample Error

For bagged models, out-of-sample error can be estimated without using **train/test split** or **cross-validation**!

For each tree, the **unused observations** are called "out-of-bag" observations.

In [194]:
# Show the first bootstrap sample.
samples[0]

array([13,  2, 12,  2,  6,  1,  3, 10, 11,  9,  6,  1,  0,  1])

In [195]:
# Show the "in-bag" observations for each sample.
for sample in samples:
    print(set(sample))


{0, 1, 2, 3, 6, 9, 10, 11, 12, 13}
{0, 1, 2, 3, 4, 7, 9, 13}
{0, 2, 3, 4, 6, 7, 8, 9, 12, 13}
{0, 1, 2, 3, 5, 6, 8, 10, 11, 12}
{2, 3, 4, 6, 10, 11, 12, 13}
{0, 1, 4, 5, 6, 7, 9, 10, 11}
{0, 1, 2, 3, 4, 5, 8, 9, 12}
{1, 2, 3, 5, 6, 7, 9, 11}
{1, 3, 6, 7, 8, 9, 11, 12}
{0, 1, 3, 4, 5, 6, 8, 10, 11, 13}


In [196]:
# Show the "out-of-bag" observations for each sample.
for sample in samples:
    print(sorted(set(range(14)) - set(sample)))

[4, 5, 7, 8]
[5, 6, 8, 10, 11, 12]
[1, 5, 10, 11]
[4, 7, 9, 13]
[0, 1, 5, 7, 8, 9]
[2, 3, 8, 12, 13]
[6, 7, 10, 11, 13]
[0, 4, 8, 10, 12, 13]
[0, 2, 4, 5, 10, 13]
[2, 7, 9, 12]


**Calculating "out-of-bag error:"**

1. For each observation in the training data, predict its response value using **only** the trees in which that observation was out-of-bag. Average those predictions (for regression) or take a vote (for classification).
2. Compare all predictions to the actual response values in order to compute the out-of-bag error.

When B is sufficiently large, the **out-of-bag error** is an accurate estimate of **out-of-sample error**.

In [197]:
# Compute the out-of-bag R-squared score (not MSE, unfortunately) for B=500.
bagreg.oob_score_

0.79869551339899825

### Aside: R-Squared

R-squared measures how much of the variance in the data is accounted for by the model:

$$R^2=1-\frac{\mbox{Mean Squared Error}}{\mbox{Mean Squared Total (i.e., Variance)}}$$


Properties:

- *Typically* greater than 0 (unless your model is worse than the null model)
- Never greater than 1.

![](./assets/r_squared.png)

**R-squared does not tell you how much of the variance in the data the model *explains*, at least in the normal sense of "explains."**

Explanations are usually *causal*, and R-squared does not distinguish between causation and association.

### Estimating Feature Importance

Bagging increases **predictive accuracy** but decreases **model interpretability** because it's no longer possible to visualize the tree to understand the importance of each feature.

However, we can still obtain an overall summary of **feature importance** from bagged models:

- **Bagged regression trees:** Calculate the total amount that **MSE** decreases due to splits over a given feature, averaged over all trees
- **Bagged classification trees:** Calculate the total amount that **Gini index** decreases due to splits over a given feature, averaged over all trees

In [198]:
bagreg.feature_importances_

AttributeError: 'BaggingRegressor' object has no attribute 'feature_importances_'

# Exercise

In your own words..

- What is ensembling?

Combining multiple predictive models together to make more accurate predictions

- How do bagged classification trees work?

Randomly selecting samples from a dataset to train numerous trees aimed at controlling/counterbalancing variance to improve predictive accuracy

- What does R-squared tell you?

The amount of variance in the data that your model captures

- What is the usual range of R-squared values?

1 and 0, can be negative if you overfit the model

- What is out-of-bag error?

The error of those sample values not included in the training sets, or bags, of the regressor trees.

<a id="part-three"></a>
## Part 3: Random Forests

Random Forests offer a **slight variation on bagged trees** with even better performance:

- Exactly like bagging, we create an ensemble of decision trees using bootstrapped samples of the training set.
- However, when building each tree, each time a split is considered, a **random sample of m features** is chosen as split candidates from the **full set of p features**. The split is only allowed to use **one of those m features**.
    - A new random sample of features is chosen for **every single tree at every single split**.
    - For **classification**, m is typically chosen to be the square root of p.
    - For **regression**, m is typically chosen to be somewhere between p/3 and p.

What's the point?

- Suppose there is **one very strong feature** in the data set. When using bagged trees, most of the trees will use that feature as the top split, resulting in an ensemble of similar trees that are **highly correlated**.
- Averaging highly correlated quantities does not significantly reduce variance (which is the entire goal of bagging).
- By randomly leaving out candidate features from each split, **random forests "decorrelate" the trees** to the extent that the averaging process can reduce the variance of the resulting model.
- Another way of looking at it is that sometimes one or two strong features dominate every tree in bagging, resulting in essentially the same tree as every predictor. (This is what was meant when saying the trees could be highly correlated.) By using a subset of features to generate each tree, we get a wider variety of predictive trees that do not all use the same dominant features.

<a id="part-four"></a>
## Part 4: Building and Tuning Decision Trees and Random Forests

In this section, we will use the sklearn implementation of random forests.

- Major League Baseball player data from 1986-87: [data](https://github.com/justmarkham/DAT8/blob/master/data/hitters.csv), [data dictionary](https://cran.r-project.org/web/packages/ISLR/ISLR.pdf) (page 7)
- Each observation represents a player.
- **Goal:** Predict player salary.

### Preparing the Data

In [ ]:
# Read in the data.
path = Path('.', 'data', 'hitters.csv')
hitters = pd.read_csv(path)
hitters


In [ ]:
# Remove rows with missing values.
hitters.isnull().sum(axis=0)
hitters.dropna(inplace=True)

In [ ]:
hitters.head()

In [ ]:
# Encode categorical variables as integers.
hitters.loc[:,'League'] = hitters.loc[:,'League'].map({'N':1,'A':0})
hitters

In [ ]:
hitters.loc[:,'Division'] = hitters.loc[:,'Division'].map({'W':1,'E':0})
hitters

In [ ]:
hitters.loc[:,'NewLeague'] = hitters.loc[:,'NewLeague'].map({'N':1,'A':0})
hitters

In [ ]:
hitters.rename(columns={'League':'NationalLeague',
                       'Division':'WestDivision',
                       'NewLeague':'NationalNewLeague'},
              inplace=True)

In [ ]:
# Create a scatter plot of hits vs years, colored by salary
hitters.plot(kind='scatter',x='Years',y='Hits',c='Salary', colormap='viridis');

In [ ]:
# Define features: Exclude career statistics (which start with "C") and the response (salary).
feature_cols = hitters.columns[hitters.columns.str.startswith('C') == False].drop('Salary')
feature_cols

In [ ]:
# Define X and y.
X = hitters.loc[:,feature_cols]
y = hitters.loc[:,'Salary']

<a id="decision-tree"></a>
## Predicting Salary With a Decision Tree

Let's first recall how we might predict salary using a single decision tree.

We'll first find the best **max_depth** for a decision tree using cross-validation:

In [ ]:
# List of values to try for max_depth:
max_depth_range = list(range(1,21))
max_depth_range

In [ ]:
# Use 10-fold cross-validation with each value of max_depth.
RMSE_scores_list = []

from sklearn.model_selection import cross_val_score

for depth in max_depth_range:
    treereg = DecisionTreeRegressor(max_depth=depth, random_state=1)
    neg_MSE_scores = cross_val_score(treereg, X, y, cv=10, scoring='neg_mean_squared_error')
    MSE_scores = -neg_MSE_scores
    RMSE_scores = np.sqrt(MSE_scores)
    mean_RMSE_score = np.mean(RMSE_scores)
    RMSE_scores_list.append(mean_RMSE_score)

In [ ]:
# Plot max_depth (x-axis) versus RMSE (y-axis).
plt.plot(max_depth_range, RMSE_scores_list);
plt.xlabel('max_depth')
plt.ylabel('RMSE(lower is better)');

In [ ]:
# Show the best RMSE and the corresponding max_depth.
sorted(list(zip(RMSE_scores_list, max_depth_range)))

In [ ]:
# max_depth=2 was best, so fit a tree using that parameter.
treereg = DecisionTreeRegressor(max_depth=2, random_state=1)
treereg.fit(X,y)

In [ ]:
# Compute feature importances.
list(zip(feature_cols, treereg.feature_importances_))

<a id="random-forest-demo"></a>
## Predicting Salary With a Random Forest

### Fitting a Random Forest With the Best Parameters

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
# max_features=5 is best and n_estimators=150 is sufficiently large.
rfreg = RandomForestRegressor(n_estimators=150, max_features=5, oob_score=True, random_state=1)
rfreg.fit(X, y)

In [ ]:
# Compute feature importances.
list(zip(feature_cols, rfreg.feature_importances_))

In [ ]:
# Compute the out-of-bag R-squared score.
rfreg.oob_score_

In [ ]:
# Find the average RMSE.
scores = cross_val_score(rfreg,X,y,cv=10,scoring='neg_mean_squared_error')
np.mean(np.sqrt(-scores))

#### Reducing X to its Most Important Features

In [ ]:
# Check the shape of X.
X.shape

** It important not to select features before separating your train from your test otherwise you are selecting features based on all known observations and introducing more of the information in the test data to the model when you fit it on the training data. **

In [199]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=89)

In [218]:
# Fit the model on only the train data
rfreg = RandomForestRegressor(n_estimators=150, max_features=5, oob_score=True, random_state=1)
rfreg.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features=5, max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=150, n_jobs=1, oob_score=True, random_state=1,
           verbose=0, warm_start=False)

In [219]:
# Set a threshold for which features to include.
from sklearn.feature_selection import SelectFromModel

sfm = SelectFromModel(rfreg, threshold='mean', prefit=True)
X_important = sfm.transform(X_train).shape

In [220]:
X_train.shape #so we went from 13 down to 5 (in the step above)

(197, 13)

Using the fit model and the features from the train data to transform the test data

In [221]:
# Check the RMSE for a random forest that only includes important features.
rfreg = RandomForestRegressor(n_estimators=150, max_features=3, random_state=1)

scores = cross_val_score(rfreg, X_important, y, cv=10, scoring='neg_mean_squared_error')
np.mean(np.sqrt(-scores))

ValueError: Found input variables with inconsistent numbers of samples: [2, 263]

In this case, the error decreased slightly. Often parameter tuning is required to achieve optimal results.

<a id="comparing"></a>
## Comparing Random Forests With Decision Trees

**Advantages of random forests:**

- Their performance is competitive with the best supervised learning methods.
- They provide a more reliable estimate of feature importance.
- They allow you to estimate out-of-sample error without using train/test split or cross-validation.

**Disadvantages of random forests:**

- They are less interpretable.
- They are slower to train.
- They are slower to predict.

# Exercise

- How does a random forest differ from ordinary bagged decision trees?

Not only is it taking random samples of the training data but it is additionally taking samples of the features

- Use a random forest classifier to predict who survives on the Titanic. Use five-fold cross-validation to evaluate its accuracy.

In [222]:
path = Path('.', 'data', 'titanic.csv')
titanic = pd.read_csv(path)

In [223]:
from sklearn.ensemble import RandomForestClassifier

In [225]:
titanic.isnull().sum(axis=0)
titanic.dropna(inplace=True)

In [226]:
titanic.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
10      1   PP 9549  16.7000    G6        S  
11      0    113783  26.5500  C103        S

In [228]:
titanic.loc[:,'Sex'] = titanic.loc[:,'Sex'].map({'female':1,'male':0})
titanic

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
21            22         1       2   
23            24         1       1   
27            28         0       1   
52            53         1       1   
54            55         0       1   
62            63         0       1   
66            67         1       2   
75            76         0       3   
88            89         1       1   
92            93         0       1   
96            97         0       1   
97            98         1       1   
102          103         0       1   
110          111         0       1   
118          119         0       1   
123          124         1       2   
124          125         0       1   
136          137         1       1   
137          138         0       1   
139          140         0       1   
148          149         0       2   
151          152         1       1   
170          171         0       1   
174          175         0       1   
177          178         0       1   
..           ...       ...     ...   
737          738         1       1   
741          742         0       1   
742          743         1       1   
745          746         0       1   
748          749         0       1   
751          752         1       3   
759          760         1       1   
763          764         1       1   
765          766         1       1   
772          773         0       2   
779          780         1       1   
781          782         1       1   
782          783         0       1   
789          790         0       1   
796          797         1       1   
802          803         1       1   
806          807         0       1   
809          810         1       1   
820          821         1       1   
823          824         1       3   
835          836         1       1   
853          854         1       1   
857          858         1       1   
862          863         1       1   
867          868         0       1   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name  Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
6                              McCarthy, Mr. Timothy J    0  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut    1   4.0      1   
11                            Bonnell, Miss. Elizabeth    1  58.0      0   
21                               Beesley, Mr. Lawrence    0  34.0      0   
23                        Sloper, Mr. William Thompson    0  28.0      0   
27                      Fortune, Mr. Charles Alexander    0  19.0      3   
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)    1  49.0      1   
54                      Ostby, Mr. Engelhart Cornelius    0  65.0      0   
62                         Harris, Mr. Henry Birkhardt    0  45.0      1   
66                        Nye, Mrs. (Elizabeth Ramell)    1  29.0      0   
75                             Moen, Mr. Sigurd Hansen    0  25.0      0   
88                          Fortune, Miss. Mabel Helen    1  23.0      3   
92                         Chaffee, Mr. Herbert Fuller    0  46.0      1   
96                           Goldschmidt, Mr. George B    0  71.0      0   
97                     Greenfield, Mr. William Bertram    0  23.0      0   
102                          White, Mr. Richard Frasar    0  21.0      0   
110                     Porter, Mr. Walter Chamberlain    0  47.0      0   
118                           Baxter, Mr. Quigg Edmond    0  24.0      0   
123                                Webber, Miss. Sus

In [236]:
pd.get_dummies(titanic.loc[:,'Embarked'])
titanic

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
21            22         1       2   
23            24         1       1   
27            28         0       1   
52            53         1       1   
54            55         0       1   
62            63         0       1   
66            67         1       2   
75            76         0       3   
88            89         1       1   
92            93         0       1   
96            97         0       1   
97            98         1       1   
102          103         0       1   
110          111         0       1   
118          119         0       1   
123          124         1       2   
124          125         0       1   
136          137         1       1   
137          138         0       1   
139          140         0       1   
148          149         0       2   
151          152         1       1   
170          171         0       1   
174          175         0       1   
177          178         0       1   
..           ...       ...     ...   
737          738         1       1   
741          742         0       1   
742          743         1       1   
745          746         0       1   
748          749         0       1   
751          752         1       3   
759          760         1       1   
763          764         1       1   
765          766         1       1   
772          773         0       2   
779          780         1       1   
781          782         1       1   
782          783         0       1   
789          790         0       1   
796          797         1       1   
802          803         1       1   
806          807         0       1   
809          810         1       1   
820          821         1       1   
823          824         1       3   
835          836         1       1   
853          854         1       1   
857          858         1       1   
862          863         1       1   
867          868         0       1   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name  Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
6                              McCarthy, Mr. Timothy J    0  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut    1   4.0      1   
11                            Bonnell, Miss. Elizabeth    1  58.0      0   
21                               Beesley, Mr. Lawrence    0  34.0      0   
23                        Sloper, Mr. William Thompson    0  28.0      0   
27                      Fortune, Mr. Charles Alexander    0  19.0      3   
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)    1  49.0      1   
54                      Ostby, Mr. Engelhart Cornelius    0  65.0      0   
62                         Harris, Mr. Henry Birkhardt    0  45.0      1   
66                        Nye, Mrs. (Elizabeth Ramell)    1  29.0      0   
75                             Moen, Mr. Sigurd Hansen    0  25.0      0   
88                          Fortune, Miss. Mabel Helen    1  23.0      3   
92                         Chaffee, Mr. Herbert Fuller    0  46.0      1   
96                           Goldschmidt, Mr. George B    0  71.0      0   
97                     Greenfield, Mr. William Bertram    0  23.0      0   
102                          White, Mr. Richard Frasar    0  21.0      0   
110                     Porter, Mr. Walter Chamberlain    0  47.0      0   
118                           Baxter, Mr. Quigg Edmond    0  24.0      0   
123                                Webber, Miss. Sus

In [237]:
titanic.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   

                                                 Name  Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
6                             McCarthy, Mr. Timothy J    0  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut    1   4.0      1   
11                           Bonnell, Miss. Elizabeth    1  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
10      1   PP 9549  16.7000    G6        S  
11      0    113783  26.5500  C103        S

In [255]:
feature_cols = ['Pclass', 'Sex', 'Age', 'SibSp','Parch', 'Fare']
X = titanic.loc[:, feature_cols]
y = titanic.loc[:,'Survived']

In [256]:
rfclass = RandomForestClassifier()

In [257]:
rfclass.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [258]:
list(zip(feature_cols, rfclass.feature_importances_))

[('Pclass', 0.02019948866948057),
 ('Sex', 0.2472316880420764),
 ('Age', 0.31857096648793604),
 ('SibSp', 0.02241394569528864),
 ('Parch', 0.032845663793464069),
 ('Fare', 0.3587382473117543)]

In [259]:
scores = cross_val_score(rfclass, X, y, cv=5, scoring='neg_mean_squared_error')
np.mean(np.sqrt(-scores))

0.51784106324476276

![Machine learning flowchart](./assets/driver_ensembling.png)

*Machine learning flowchart created by the [second-place finisher](http://blog.kaggle.com/2015/04/20/axa-winners-interview-learning-telematic-fingerprints-from-gps-data/) of Kaggle's [Driver Telematics competition](https://www.kaggle.com/c/axa-driver-telematics-analysis)*.

<a id="tuning"></a>
## Optional: Tuning Individual Parameters

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfreg = RandomForestRegressor()
rfreg

### Tuning n_estimators

One important tuning parameter is **n_estimators**, which represents the number of trees that should be grown. This should be a large enough value that the error seems to have "stabilized."

In [ ]:
# List of values to try for n_estimators:
estimator_range = list(range(10, 310, 10))

# List to store the average RMSE for each value of n_estimators:
RMSE_scores = []

# Use five-fold cross-validation with each value of n_estimators (Warning: Slow!).
for estimator in estimator_range:
    rfreg = RandomForestRegressor(n_estimators=estimator, random_state=1)
    MSE_scores = cross_val_score(rfreg, X, y, cv=5, scoring='neg_mean_squared_error')
    RMSE_scores.append(np.mean(np.sqrt(-MSE_scores)))

In [ ]:
# Plot RMSE (y-axis) versus n_estimators (x-axis).

plt.plot(estimator_range, RMSE_scores);

plt.xlabel('n_estimators');
plt.ylabel('RMSE (lower is better)');

**Adding more trees will only help average performance, with diminishing returns.**

### Tuning max_features

The other important tuning parameter is **max_features**, which represents the number of features that should be considered at each split.

In [ ]:
# List of values to try for max_features:
feature_range = list(range(1, len(feature_cols)+1))

# List to store the average RMSE for each value of max_features:
RMSE_scores = []

# Use 10-fold cross-validation with each value of max_features (Warning: Super slow!).
for feature in feature_range:
    rfreg = RandomForestRegressor(n_estimators=150, max_features=feature, random_state=1)
    MSE_scores = cross_val_score(rfreg, X, y, cv=10, scoring='neg_mean_squared_error')
    RMSE_scores.append(np.mean(np.sqrt(-MSE_scores)))

In [ ]:
# Plot max_features (x-axis) versus RMSE (y-axis).

plt.plot(feature_range, RMSE_scores);

plt.xlabel('max_features');
plt.ylabel('RMSE (lower is better)');

In [ ]:
# Show the best RMSE and the corresponding max_features.
sorted(zip(RMSE_scores, feature_range))[0]

<a id="summary"></a>
## Summary

**Which model is best?** The best classifier for a particular task is task-dependent. In many business cases, interpretability is more important than accuracy. So, decision trees may be preferred. In other cases, accuracy on unseen data might be paramount, in which case random forests would likely be better (since they typically overfit less). 

---

**In this lesson:**

- We looked at ensemble models.

- We saw how decision trees could be extended using two ensemble techniques -- bagging and random forests.

- We looked at methods of evaluating feature importance and tuning parameters.

# Projects

- Final Project t. 5 due Thurs.
    
**Guidelines:**

- https://git.generalassemb.ly/datr1618/final_project/blob/master/requirements.md#presentation
- 5-6 minutes, with a hard cutoff at 6.
- Share your screen, using slides, Jupyter notebook, etc.
- If you use a Jupyter notebook, it should be polished for presentation.

# Questions?

# Exit Tickets

```
=========================================
@channel
Exit Ticket: https://goo.gl/forms/OUw4gyTiRKMOTI3t2        

#feedback
=========================================
```